[package]
name = "nmap_rs"
version = "0.1.0"
authors = ["KingDotCom <levequeloris66@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = "1.0.4"